### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by radare** [enwin/emoji#2]
```
$ npm install

> icomoon-phantomjs@0.4.2 preinstall /Users/pancake/prg/ffos/emoji/node_modules/grunt-fontsmith/node_modules/fontsmith/node_modules/icomoon-phantomjs
> node utils/preinstall.js

Cannot detect PhantomJS version. Please install PhantomJS >= 1.9.0
/Users/pancake/prg/ffos/emoji/node_modules/grunt-fontsmith/node_modules/fontsmith/node_modules/icomoon-phantomjs/utils/preinstall.js:14
    throw err;
          ^
Error: Command failed: /bin/sh -c phantomjs --version
/bin/sh: phantomjs: command not found

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
^C
```

**Comment by enwin** [comment]
Forgot the hard dependency to phantomjs :/ you should be able to install it globaly via homebrew or npm.

**Comment by radare** [comment]
Thanks! npm install grunt-cli after that and i got the thing working.
